#!/usr/bin/env python3
"""Save an isolated CARE stack configuration without starting any services.

Read care-scaffold.env in the workspace root. Explicit ports win; blank or missing
ports are allocated and saved. Reruns preserve assignments, even while running.
Use --check-ports before a cold start to check all saved ports without rewriting
configuration. Compose and Vite --strictPort still catch later conflicts.
Requires Docker Compose >= 2.24.4.
"""

import argparse
import errno
import hashlib
import os
from pathlib import Path
import re
import shlex
import socket
import tempfile


PORT_KEYS = (
    "CARE_API_PORT", "CARE_FE_PORT", "PLUGIN_PORT", "CARE_DB_PORT",
    "CARE_REDIS_PORT", "CARE_S3_PORT", "CARE_S3_CONSOLE_PORT", "CARE_DEBUG_PORT",
)


def port_available(port):
    """Check both loopback families, keeping both sockets open during the probe."""
    sockets = []
    try:
        for family, address in ((socket.AF_INET, "127.0.0.1"), (socket.AF_INET6, "::1")):
            try:
                probe = socket.socket(family, socket.SOCK_STREAM)
                sockets.append(probe)
                if family == socket.AF_INET6:
                    probe.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
                probe.bind((address, port))
            except OSError as exc:
                if family == socket.AF_INET6 and exc.errno in (
                    errno.EAFNOSUPPORT, errno.EPROTONOSUPPORT, errno.EADDRNOTAVAIL,
                ):
                    continue
                if exc.errno == errno.EADDRINUSE:
                    return False
                raise
        return True
    finally:
        for probe in sockets:
            probe.close()


def allocate_ports(seed, configured=None):
    configured = dict(configured or {})
    missing = [key for key in PORT_KEYS if key not in configured]
    if not missing:
        return configured
    reserved = set(map(int, configured.values()))
    # Prefer a compact block, skipping occupied and explicitly assigned ports.
    count = 30000 // len(PORT_KEYS)
    for offset in range(count):
        start = 20000 + ((seed + offset) % count) * len(PORT_KEYS)
        ports = [port for port in range(start, start + len(PORT_KEYS))
                 if port not in reserved and port_available(port)]
        if len(ports) >= len(missing):
            return {**configured, **dict(zip(missing, map(str, ports)))}
    raise ValueError("Not enough available ports in 20000–49999")


def read_env(path):
    values = {}
    for line in path.read_text().splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, raw = line.partition("=")
        key = key.strip()
        if not separator or not re.fullmatch(r"[A-Z][A-Z0-9_]*", key) or key in values:
            raise ValueError(f"Invalid or duplicate entry in {path}: {key}")
        value = shlex.split(raw, comments=True)
        if len(value) > 1:
            raise ValueError(f"Invalid value for {key} in {path}")
        values[key] = value[0] if value else ""
    return values


OVERRIDE = """# Generated by configure-workspace.py. Compose >= 2.24.4 is required.
# !override REPLACES upstream port lists; ordinary lists would retain shared ports.
services:
  backend:
    image: ${COMPOSE_PROJECT_NAME}_backend:local
    ports: !override
      - "127.0.0.1:${CARE_API_PORT}:9000"
      - "127.0.0.1:${CARE_DEBUG_PORT}:9876"
    environment: &storage_endpoints
      BUCKET_EXTERNAL_ENDPOINT: http://localhost:${CARE_S3_PORT}
      FILE_UPLOAD_BUCKET_EXTERNAL_ENDPOINT: http://localhost:${CARE_S3_PORT}
      FACILITY_S3_BUCKET_EXTERNAL_ENDPOINT: http://localhost:${CARE_S3_PORT}
  celery:
    image: ${COMPOSE_PROJECT_NAME}_backend:local
    ports: !override []
    environment: *storage_endpoints
  db:
    ports: !override
      - "127.0.0.1:${CARE_DB_PORT}:5432"
  redis:
    ports: !override
      - "127.0.0.1:${CARE_REDIS_PORT}:6379"
  minio:
    ports: !override
      - "127.0.0.1:${CARE_S3_PORT}:9000"
      - "127.0.0.1:${CARE_S3_CONSOLE_PORT}:9001"
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
volumes:
  postgres-data:
    name: ${COMPOSE_PROJECT_NAME}_postgres-data
  redis-data:
    name: ${COMPOSE_PROJECT_NAME}_redis-data
"""

WRAPPER = r'''#!/usr/bin/env bash
# All stack operations must use this wrapper, including build, exec, logs and down.
set -euo pipefail
STACK_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
set -a
source "$STACK_DIR/../care-scaffold.env"
set +a
compose_version="$(docker compose version --short)"
if [[ ! "$compose_version" =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
  echo "Cannot determine Docker Compose version: $compose_version" >&2
  exit 1
fi
major=${BASH_REMATCH[1]} minor=${BASH_REMATCH[2]} patch=${BASH_REMATCH[3]}
if (( major < 2 || (major == 2 && minor < 24) || (major == 2 && minor == 24 && patch < 4) )); then
  echo "Docker Compose >= 2.24.4 is required for isolated port overrides." >&2
  exit 1
fi
exec docker compose \
  --project-name "$COMPOSE_PROJECT_NAME" \
  --project-directory "$CARE_BE" \
  --env-file "$STACK_DIR/../care-scaffold.env" \
  -f "$CARE_BE/docker-compose.yaml" \
  -f "$CARE_BE/docker-compose.local.yaml" \
  -f "$STACK_DIR/compose.override.yaml" "$@"
'''


def read_configuration(workspace):
    workspace = Path(workspace).expanduser().resolve()
    # Keep care-scaffold.env valid as both shell input and a Compose dotenv file.
    if any(char in str(workspace) for char in "\n\r'\\"):
        raise ValueError("Workspace paths cannot contain newlines, apostrophes or backslashes")
    stack_dir = workspace / ".agent"
    env_path = workspace / "care-scaffold.env"
    legacy_path = stack_dir / "stack.env"
    for path in (workspace / "care", workspace / "care_fe", stack_dir, env_path,
                 legacy_path, stack_dir / "compose.override.yaml", stack_dir / "compose.sh"):
        if path.is_symlink():
            raise ValueError(f"Use dedicated workspace paths, not symlinks: {path}")
    if env_path.exists() and legacy_path.exists():
        raise ValueError(f"Both {env_path} and {legacy_path} exist; reconcile them into care-scaffold.env first")
    digest = hashlib.sha256(str(workspace).encode()).hexdigest()
    identity = {
        "WORKSPACE": str(workspace),
        "CARE_BE": str(workspace / "care"),
        "CARE_FE": str(workspace / "care_fe"),
        "COMPOSE_PROJECT_NAME": f"care_scaffold_{digest[:12]}",
    }
    source = legacy_path if legacy_path.exists() else env_path
    values = read_env(source) if source.exists() else {}
    allowed = set(identity) | set(PORT_KEYS) | {"CARE_API_URL", "CARE_FE_URL", "BACKUP_DIR"}
    if unknown := set(values) - allowed:
        raise ValueError(f"{source}: unknown setting(s): {', '.join(sorted(unknown))}")
    for key, expected in identity.items():
        if values.get(key) and values[key] != expected:
            raise ValueError(f"{source}: {key} does not match this dedicated workspace")
    ports = {key: values[key] for key in PORT_KEYS if values.get(key)}
    if any(not port.isascii() or not port.isdecimal() or not 1024 <= int(port) <= 65535
           for port in ports.values()):
        raise ValueError(f"{source}: ports must be integers in 1024–65535")
    if len({int(port) for port in ports.values()}) != len(ports):
        raise ValueError(f"{source}: ports must be distinct")
    ports = {key: str(int(port)) for key, port in ports.items()}
    saved = len(ports) == len(PORT_KEYS) and all(values.get(key) == expected for key, expected in identity.items())
    return workspace, identity, ports, saved


def check_ports(ports):
    for key, port in ports.items():
        if not port_available(int(port)):
            raise ValueError(f"{key}={port} is already in use; choose another port or stop only its owning workspace")


def configure(workspace):
    workspace, identity, ports, saved = read_configuration(workspace)
    if not saved:
        check_ports(ports)
    if len(ports) != len(PORT_KEYS):
        ports = allocate_ports(int(identity["COMPOSE_PROJECT_NAME"].removeprefix("care_scaffold_"), 16), ports)
    values = {
        **identity, **ports,
        "CARE_API_URL": f"http://localhost:{ports['CARE_API_PORT']}",
        "CARE_FE_URL": f"http://localhost:{ports['CARE_FE_PORT']}",
        "BACKUP_DIR": str(workspace / "care" / "care-backups"),
    }
    env = "# Edit ports here, then rerun configure-workspace.py and refresh frontend/plugin wiring.\n"
    env += "# Blank ports are allocated automatically. Saved ports stay fixed on rerun.\n"
    # Always single-quote to prevent shell expansion and Compose interpolation of paths.
    env += "".join(f"{key}='{value}'\n" for key, value in values.items())
    stack_dir = workspace / ".agent"
    targets = (workspace / "care-scaffold.env", stack_dir / "compose.override.yaml", stack_dir / "compose.sh")
    stack_dir.mkdir(parents=True, exist_ok=True)
    for target, content, mode in zip(targets, (env, OVERRIDE, WRAPPER), (0o644, 0o644, 0o755)):
        with tempfile.NamedTemporaryFile(mode="w", dir=stack_dir, delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
        try:
            temporary.chmod(mode)
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)
    # Remove the old source only after all replacement artifacts have been written.
    (stack_dir / "stack.env").unlink(missing_ok=True)
    return values


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--check-ports", action="store_true", help="Check saved ports before a cold start, without changing files")
    args = parser.parse_args()
    try:
        if args.check_ports:
            _, _, ports, _ = read_configuration(args.workspace)
            if len(ports) != len(PORT_KEYS):
                raise ValueError("Configure all eight ports before checking availability")
            check_ports(ports)
            print("All saved ports are available. Startup must still check for later conflicts.")
            return
        values = configure(args.workspace)
    except (OSError, ValueError) as exc:
        parser.exit(1, f"error: {exc}\n")
    print(f"Saved {values['WORKSPACE']}/care-scaffold.env")
    print(f"API {values['CARE_API_URL']} | UI {values['CARE_FE_URL']} | plugin :{values['PLUGIN_PORT']}")
    print("Saved ports are preserved. Startup must fail if another process takes a port.")


if __name__ == "__main__":
    main()
